---
dependency:
  name: galaxy
  enabled: false
driver:
  name: podman
platforms:
  - name: ubuntu_python
    image: docker.io/python:3.8-slim
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroy
